# Generated by Django 5.0.3 on 2024-03-19 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('gambar_produk', models.ImageField(null=True, upload_to='gambar/banner')),
                ('harga_beli', models.IntegerField(blank=True, null=True)),
                ('harga_jual', models.IntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produks', to='core.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_transaksi', models.CharField(max_length=200, null=True)),
                ('total_transaksi', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Baru', 'Baru'), ('Lunas', 'Lunas')], default='Baru', max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('tanggal_penjualan', models.DateTimeField(null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi_penjualan_customers', to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='DetailTransaksiPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField(blank=True, null=True)),
                ('produk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi_penjualan_produk', to='core.produk')),
                ('transaksi_penjualan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail_penjualans', to='core.transaksipenjualan')),
            ],
        ),
    ]
